name: CI

on:
  push:
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: '1.17'
  GOLANGCI_VERSION: 'v1.50'

jobs:
  golangci-lint:
      runs-on: ubuntu-22.04
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            submodules: true
        - name: Setup Go
          uses: actions/setup-go@v2
          with:
            go-version: ${{ env.GO_VERSION }}
        - name: Lint golang code
          uses: golangci/golangci-lint-action@v2
          with:
            version: ${{ env.GOLANGCI_VERSION }}
            args: --disable-all  -E deadcode -E gofmt -E goimports -E ineffassign -E misspell -E vet --timeout=15m